application: lecturelogger
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img 
  static_dir: assets/img
- url: /js
  static_dir: assets/js  
- url: /css
  static_dir: assets/css
- url: /fonts
  static_dir: assets/fonts
- url: challenges.html
  static_dir: assets/challenges.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest